---
kind: pipeline
type: docker
name: default

clone:
  disable: true

steps:
- name: clone
  image: golang:1.13
  commands:
  - pkg=github.com/dolanor/mitm
  - ws=/drone/src/go/src/$pkg
  - git clone https://$pkg $ws
  - cd $ws
  - git checkout $DRONE_COMMIT

- name: deps
  image: golang:1.13
  commands:
  - export GOPATH=/drone/src/go
  - go env
  - pwd; ls;
  - cd /drone/src/go/src/github.com/dolanor/mitm
  - go get -v
  - go test
  - go build

- name: test
  image: golang:1.13
  commands:
  - go test

- name: build
  image: golang:1.13
  commands:
  - go build

