---
kind: pipeline
type: docker
name: default

steps:
- name: deps
  image: golang:1.13
  commands:
  - go get -v
  - go test
  - go build

- name: test
  image: golang:1.13
  commands:
  - go test

- name: build
  image: golang:1.13
  commands:
  - go build

