---
kind: pipeline
type: docker
name: default

clone:
  disable: true

steps:
- name: clone
  image: golang:1.13
  commands:
  - echo $PWD
  - echo pkg=github.com/dolanor/mitm >> .env
  - echo ws=/drone/src/go/src/$pkg >> .env
  - export GOPATH=/drone/src/go >> .env
  - . $PWD/.env
  - git clone https://$pkg $ws
  - cd $ws
  - git checkout $DRONE_COMMIT

- name: deps
  image: golang:1.13
  commands:
  - .env && cd $ws
  - go env
  - pwd; ls;
  - cd /drone/src/go/src/github.com/dolanor/mitm
  - go get -v
  - go test
  - go build

- name: test
  image: golang:1.13
  commands:
  - .env && cd $ws
  - go test

- name: build
  image: golang:1.13
  commands:
  - .env && cd $ws
  - go build

